### ISSUE TITLE
Clarify license status

### ISSUE THREAD

**Issue by TheMageKing** [feramhq/transity#25]
This was brought up recently on debian-legal: it is unclear what the licensing conditions of Transity are.  Specifically, it appears that you are violating the terms of your own license.

It's fairly clear that GPL-3+ is the licence you are distributing the code under: its is what's listed in you description.  However, you add the additional condition that long-term users purchase a license.  That is not a legal request to make of GPL-3+ licensed code: the GPL explicitly prohibits additional restrictions.  Granted, you could be choosing to distribute your code under a new license that is based on the GPL, but in that case, you would need to comply with a few additional rules (which you don't), and other projects would be unable to use your code as part of their software (defeating the point of the open-source system).

In short, you can't require your end users to do much of anything, or place restrictions on the redistribution of your code, without violating the terms of the GPL. As soon as a person owns software covered by the GPL, they have the ability to use, modify, and redistribute it as they please: even if you say in the README that they have to purchase a license, they don't: they already have one.

Fear not, however: there is an easy solution to permit you to distribute your code as GPL3+ while also requesting donations and prohibiting commercial redistribution.  Simply rephrase your additional line that requires that long-term users purchase a license to one that asks for donations, and uses the currently existing price as a recommended donation.  That would let Transity be included in debian, which would also cause Transity to be distributed as part of Ubuntu, Mint, and almost any other distro that isn't Arch or Fedora.

Its worth noting that you keep the ability to sell a commercial license to Transity, no matter what solution you pick.   You can also chose to stop offering your code under the GPL altogether, and simply have it exist as a source-available paid software product (whose source is copyrighted and may not be redistributed) or even just as a standard proprietary software application.  You could even distribute the GPL'd source only to those who buy your product.  The thing you can't do is give people GPL'd code, then ask them to give you money later.

**Comment by ad-si** [comment]
Thanks for bringing this up to me. I'm aware that I can't require anything and I'm acknowledging this on cliapp.store:

> You can try out Transity for free. To use it regularly, you must buy a license. 
> There is no way for us to enforce this, but we're counting on your honesty to acknowledge when you should pay for it.

Granted, the "must" is a questionable word choice as legally speaking they don't have to. I wanted to make a stronger word choice than "you can donate", cause then nobody will 😔. But yeah, it's not a good wording, I will change it later. Basically I wanted to convey that a donation is expected on longterm usage (which sounds awful, cause that's not what people understand as a donation). 

FSF itself calls it "distributing free software for a fee": https://www.gnu.org/philosophy/selling.en.html
Maybe I'll pick something along those lines...

> That would let Transity be included in debian, which would also cause Transity to be distributed as part of Ubuntu, Mint, and almost any other distro that isn't Arch or Fedora.

I haven't gotten any feedback so far that anyone is seriously using Transity except me 😅. Can you link to the discussion? Would be glad to hear about people using it! 🙃

**Comment by ad-si** [comment]
I just switch to the AGPL and updated the license documentation with a hopefully better explanation: https://github.com/feramhq/transity/commit/8dde588f2e52670745cb501a9d2439847f948cce
What do you think?

**Comment by ad-si** [comment]
@TheMageKing 👍Awesome, thanks a lot for making the effort!
