### ISSUE TITLE
NPM installation fails on Windows 10 (missing "make"?)

### ISSUE THREAD

**Issue by cdokolas** [feramhq/transity#3]
I get the following upon running `npm install --global transity`:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! transity@0.2.1 postinstall: `make postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the transity@0.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```
Typing "make" on the command line gives `'make' is not recognized as an internal or external command,
operable program or batch file.`

Platform: Windows 10, 64-bit

**Comment by ad-si** [comment]
Should be fixed by 01c8c6131e8da7141983219dac72b65bda22a7ba.
Thanks for the bug report!
