### ISSUE TITLE
Ledger import script is not working

### ISSUE THREAD

**Issue by adrm** [feramhq/transity#4]
In bash it's impossible to paste it, since it gets an error in this line and parsing break from that.
![sin nombre](https://user-images.githubusercontent.com/307945/41153214-65eba8a4-6b16-11e8-99e4-b5d9c6849a8e.png)

In zsh it also gives an error:
![imagen](https://user-images.githubusercontent.com/307945/41153271-89eb6c8a-6b16-11e8-897c-9347fa92992a.png)

Am I doing something wrong?

**Comment by ad-si** [comment]
Ah, dammit. I only tested it with fish and assumed it would work with other shells as well. I moved it into a separate file in f96ab97.

**Comment by adrm** [comment]
Ok, will try. Thanks!
